# Generated by Django 4.1.7 on 2023-02-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_isadmin_user_isapprover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isApprover',
            new_name='is_approver',
        ),
    ]
