# Generated by Django 4.1.7 on 2023-02-20 03:53

import change_request.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.IntegerField(primary_key=change_request.models.User, serialize=False)),
                ('date_requested', models.DateField()),
                ('expiration_date', models.DateField()),
                ('area', models.CharField(choices=[('ETM', 'ETM'), ('CD6R 2pc', 'CD6R 2pc'), ('P702', 'P702'), ('Supermarket', 'Supermarket'), ('LD71', 'LD71')], max_length=20)),
                ('reason_for_request', models.CharField(max_length=800)),
                ('description_of_change', models.CharField(max_length=800)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApprover', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
