# Generated by Django 4.1.7 on 2023-02-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_request', '0003_alter_request_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tasks',
            field=models.CharField(default='first attempt', max_length=800),
            preserve_default=False,
        ),
    ]
